/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.TelaMenu;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class JpRegistrar extends javax.swing.JPanel {

    /**
     * Creates new form jpRegistrar
     */
    public JpRegistrar() {
        initComponents();
        jbLogin.setFocusPainted(false);
        jbLogin.setBorderPainted(false);
        jbLogin.setContentAreaFilled(false);
        jbLogin.setOpaque(false);
        jbLogin.setBackground(null);
        jbLogin.setBorder(null);
    }

    public void addEventoVoltarLogin(ActionListener acv) {
        jbLogin.addActionListener(acv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jlCadastrar = new javax.swing.JLabel();
        myTextField1 = new view.Componentes.MyTextField();
        myTextField2 = new view.Componentes.MyTextField();
        myPasswordField1 = new view.Componentes.MyPasswordField();
        myPasswordField2 = new view.Componentes.MyPasswordField();
        myButton1 = new view.Componentes.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(291, 420));
        setMinimumSize(new java.awt.Dimension(291, 420));
        setPreferredSize(new java.awt.Dimension(291, 420));
        setRequestFocusEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(291, 380));
        jPanel2.setMinimumSize(new java.awt.Dimension(291, 380));
        jPanel2.setPreferredSize(new java.awt.Dimension(291, 380));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jlCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlCadastrar.setForeground(new java.awt.Color(8, 136, 183));
        jlCadastrar.setText("Cadastrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(jlCadastrar, gridBagConstraints);

        myTextField1.setText("myTextField1");
        myTextField1.setMaximumSize(new java.awt.Dimension(200, 35));
        myTextField1.setMinimumSize(new java.awt.Dimension(200, 35));
        myTextField1.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(myTextField1, gridBagConstraints);

        myTextField2.setText("myTextField2");
        myTextField2.setImagem(new javax.swing.ImageIcon(getClass().getResource("/view/Imagens/Email25px.png"))); // NOI18N
        myTextField2.setMaximumSize(new java.awt.Dimension(200, 35));
        myTextField2.setMinimumSize(new java.awt.Dimension(200, 35));
        myTextField2.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(myTextField2, gridBagConstraints);

        myPasswordField1.setText("myPasswordField1");
        myPasswordField1.setImagem(new javax.swing.ImageIcon(getClass().getResource("/view/Imagens/SenhaFechada25px.png"))); // NOI18N
        myPasswordField1.setMaximumSize(new java.awt.Dimension(200, 35));
        myPasswordField1.setMinimumSize(new java.awt.Dimension(200, 35));
        myPasswordField1.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(myPasswordField1, gridBagConstraints);

        myPasswordField2.setText("myPasswordField2");
        myPasswordField2.setImagem(new javax.swing.ImageIcon(getClass().getResource("/view/Imagens/SenhaFechada25px.png"))); // NOI18N
        myPasswordField2.setMaximumSize(new java.awt.Dimension(200, 35));
        myPasswordField2.setMinimumSize(new java.awt.Dimension(200, 35));
        myPasswordField2.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(myPasswordField2, gridBagConstraints);

        myButton1.setText("Cadastrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(myButton1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 136, 183));
        jLabel2.setText("Nome de Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 136, 183));
        jLabel3.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 136, 183));
        jLabel4.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(8, 136, 183));
        jLabel5.setText("Senha Novamente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        jPanel2.add(jLabel5, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(291, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(291, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(291, 35));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

        jbLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(8, 136, 183));
        jbLogin.setText("Login");
        jbLogin.setBorderPainted(false);
        jbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jbLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbLogin;
    private javax.swing.JLabel jlCadastrar;
    private view.Componentes.MyButton myButton1;
    private view.Componentes.MyPasswordField myPasswordField1;
    private view.Componentes.MyPasswordField myPasswordField2;
    private view.Componentes.MyTextField myTextField1;
    private view.Componentes.MyTextField myTextField2;
    // End of variables declaration//GEN-END:variables
}
