/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao.TelaMenuCadastroLogin;

import java.awt.event.ActionListener;

/**
 *
 * @author Usuario
 */
public class JpLogin extends javax.swing.JPanel {

    /**
     * Creates new form jpLogin
     */
    public JpLogin() {
        initComponents();
        jlCadastrar.setFocusPainted(false);
        jlCadastrar.setBorderPainted(false);
        jlCadastrar.setContentAreaFilled(false);
        jlCadastrar.setOpaque(false);
        jlCadastrar.setBackground(null);
        jlCadastrar.setBorder(null);
    }

    public void addEventoIrCadastrar(ActionListener evt) {
        jlCadastrar.addActionListener(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpPainelCima = new javax.swing.JPanel();
        jlLogin = new javax.swing.JLabel();
        myTextField1 = new visao.Componentes.MyTextField();
        myPasswordField1 = new visao.Componentes.MyPasswordField();
        jbBotaoAcessar = new visao.Componentes.MyButton();
        jlSenha = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jpPainelBaixo = new javax.swing.JPanel();
        jlCadastrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(291, 420));

        jpPainelCima.setBackground(new java.awt.Color(255, 255, 255));
        jpPainelCima.setMaximumSize(new java.awt.Dimension(248, 288));
        jpPainelCima.setMinimumSize(new java.awt.Dimension(248, 288));
        jpPainelCima.setPreferredSize(new java.awt.Dimension(291, 288));
        jpPainelCima.setLayout(new java.awt.GridBagLayout());

        jlLogin.setBackground(new java.awt.Color(255, 255, 255));
        jlLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlLogin.setForeground(new java.awt.Color(8, 136, 183));
        jlLogin.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jpPainelCima.add(jlLogin, gridBagConstraints);

        myTextField1.setText("myTextField1");
        myTextField1.setImagem(new javax.swing.ImageIcon(getClass().getResource("/visao/Imagens/Email25px.png"))); // NOI18N
        myTextField1.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpPainelCima.add(myTextField1, gridBagConstraints);

        myPasswordField1.setText("myPasswordField1");
        myPasswordField1.setImagem(new javax.swing.ImageIcon(getClass().getResource("/visao/Imagens/SenhaFechada25px.png"))); // NOI18N
        myPasswordField1.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpPainelCima.add(myPasswordField1, gridBagConstraints);

        jbBotaoAcessar.setText("Acessar");
        jbBotaoAcessar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbBotaoAcessar.setMinimumSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(16, 1, 16, 1);
        jpPainelCima.add(jbBotaoAcessar, gridBagConstraints);

        jlSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlSenha.setForeground(new java.awt.Color(8, 136, 183));
        jlSenha.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpPainelCima.add(jlSenha, gridBagConstraints);

        jlEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(8, 136, 183));
        jlEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jpPainelCima.add(jlEmail, gridBagConstraints);

        jpPainelBaixo.setBackground(new java.awt.Color(255, 255, 255));
        jpPainelBaixo.setMaximumSize(new java.awt.Dimension(248, 40));
        jpPainelBaixo.setMinimumSize(new java.awt.Dimension(248, 40));
        jpPainelBaixo.setPreferredSize(new java.awt.Dimension(291, 40));
        jpPainelBaixo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 10));

        jlCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCadastrar.setForeground(new java.awt.Color(8, 136, 183));
        jlCadastrar.setText("Cadastrar");
        jlCadastrar.setBorderPainted(false);
        jlCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpPainelBaixo.add(jlCadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPainelCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpPainelBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpPainelCima, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpPainelBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private visao.Componentes.MyButton jbBotaoAcessar;
    private javax.swing.JButton jlCadastrar;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPanel jpPainelBaixo;
    private javax.swing.JPanel jpPainelCima;
    private visao.Componentes.MyPasswordField myPasswordField1;
    private visao.Componentes.MyTextField myTextField1;
    // End of variables declaration//GEN-END:variables
}
