/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.TelaMensagens;

/**
 *
 * @author Usuario
 */
public class JpTelaMensagens extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JpTelaMensagens.class.getName());

    /**
     * Creates new form TelaMensagens
     */
    public JpTelaMensagens() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuLateralEsquerdo1 = new visao.TelaMensagens.JpMenuLateralEsquerdo();
        JPainelContatos = new javax.swing.JPanel();
        JpLogoProjeto = new javax.swing.JPanel();
        jlConectaUFMS = new javax.swing.JLabel();
        JpBuscarContatos = new javax.swing.JPanel();
        JpContatosFrequentes = new javax.swing.JPanel();
        JpConversa = new javax.swing.JPanel();
        JpPerfilContato = new javax.swing.JPanel();
        JpConversaAtual = new javax.swing.JPanel();
        JpEnviarMensagens = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpMenuLateralEsquerdo1.setMaximumSize(new java.awt.Dimension(60, 32767));
        jpMenuLateralEsquerdo1.setMinimumSize(new java.awt.Dimension(60, 600));

        javax.swing.GroupLayout jpMenuLateralEsquerdo1Layout = new javax.swing.GroupLayout(jpMenuLateralEsquerdo1);
        jpMenuLateralEsquerdo1.setLayout(jpMenuLateralEsquerdo1Layout);
        jpMenuLateralEsquerdo1Layout.setHorizontalGroup(
            jpMenuLateralEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jpMenuLateralEsquerdo1Layout.setVerticalGroup(
            jpMenuLateralEsquerdo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jpMenuLateralEsquerdo1);

        JPainelContatos.setMaximumSize(new java.awt.Dimension(260, 50000));
        JPainelContatos.setMinimumSize(new java.awt.Dimension(260, 600));
        JPainelContatos.setLayout(new javax.swing.BoxLayout(JPainelContatos, javax.swing.BoxLayout.Y_AXIS));

        JpLogoProjeto.setBackground(new java.awt.Color(0, 82, 122));
        JpLogoProjeto.setMaximumSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setMinimumSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setPreferredSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setRequestFocusEnabled(false);

        jlConectaUFMS.setBackground(new java.awt.Color(255, 255, 255));
        jlConectaUFMS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlConectaUFMS.setForeground(new java.awt.Color(255, 255, 255));
        jlConectaUFMS.setText("ConectaUFMS");

        javax.swing.GroupLayout JpLogoProjetoLayout = new javax.swing.GroupLayout(JpLogoProjeto);
        JpLogoProjeto.setLayout(JpLogoProjetoLayout);
        JpLogoProjetoLayout.setHorizontalGroup(
            JpLogoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLogoProjetoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlConectaUFMS)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        JpLogoProjetoLayout.setVerticalGroup(
            JpLogoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLogoProjetoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jlConectaUFMS)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JPainelContatos.add(JpLogoProjeto);

        JpBuscarContatos.setBackground(new java.awt.Color(255, 255, 255));
        JpBuscarContatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpBuscarContatos.setMaximumSize(new java.awt.Dimension(260, 50));
        JpBuscarContatos.setMinimumSize(new java.awt.Dimension(260, 50));
        JpBuscarContatos.setPreferredSize(new java.awt.Dimension(260, 50));

        javax.swing.GroupLayout JpBuscarContatosLayout = new javax.swing.GroupLayout(JpBuscarContatos);
        JpBuscarContatos.setLayout(JpBuscarContatosLayout);
        JpBuscarContatosLayout.setHorizontalGroup(
            JpBuscarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        JpBuscarContatosLayout.setVerticalGroup(
            JpBuscarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        JPainelContatos.add(JpBuscarContatos);

        JpContatosFrequentes.setBackground(new java.awt.Color(255, 255, 255));
        JpContatosFrequentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpContatosFrequentes.setMaximumSize(new java.awt.Dimension(260, 5000));
        JpContatosFrequentes.setMinimumSize(new java.awt.Dimension(260, 490));

        javax.swing.GroupLayout JpContatosFrequentesLayout = new javax.swing.GroupLayout(JpContatosFrequentes);
        JpContatosFrequentes.setLayout(JpContatosFrequentesLayout);
        JpContatosFrequentesLayout.setHorizontalGroup(
            JpContatosFrequentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        JpContatosFrequentesLayout.setVerticalGroup(
            JpContatosFrequentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        JPainelContatos.add(JpContatosFrequentes);

        getContentPane().add(JPainelContatos);

        JpConversa.setMaximumSize(new java.awt.Dimension(50000, 50000));
        JpConversa.setMinimumSize(new java.awt.Dimension(680, 600));
        JpConversa.setLayout(new javax.swing.BoxLayout(JpConversa, javax.swing.BoxLayout.Y_AXIS));

        JpPerfilContato.setBackground(new java.awt.Color(255, 255, 255));
        JpPerfilContato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpPerfilContato.setMaximumSize(new java.awt.Dimension(32767, 60));
        JpPerfilContato.setMinimumSize(new java.awt.Dimension(680, 60));
        JpPerfilContato.setPreferredSize(new java.awt.Dimension(680, 60));

        javax.swing.GroupLayout JpPerfilContatoLayout = new javax.swing.GroupLayout(JpPerfilContato);
        JpPerfilContato.setLayout(JpPerfilContatoLayout);
        JpPerfilContatoLayout.setHorizontalGroup(
            JpPerfilContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpPerfilContatoLayout.setVerticalGroup(
            JpPerfilContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        JpConversa.add(JpPerfilContato);

        JpConversaAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout JpConversaAtualLayout = new javax.swing.GroupLayout(JpConversaAtual);
        JpConversaAtual.setLayout(JpConversaAtualLayout);
        JpConversaAtualLayout.setHorizontalGroup(
            JpConversaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpConversaAtualLayout.setVerticalGroup(
            JpConversaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        JpConversa.add(JpConversaAtual);

        JpEnviarMensagens.setBackground(new java.awt.Color(255, 255, 255));
        JpEnviarMensagens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JpEnviarMensagens.setMaximumSize(new java.awt.Dimension(32767, 50));
        JpEnviarMensagens.setMinimumSize(new java.awt.Dimension(680, 50));
        JpEnviarMensagens.setPreferredSize(new java.awt.Dimension(680, 50));

        javax.swing.GroupLayout JpEnviarMensagensLayout = new javax.swing.GroupLayout(JpEnviarMensagens);
        JpEnviarMensagens.setLayout(JpEnviarMensagensLayout);
        JpEnviarMensagensLayout.setHorizontalGroup(
            JpEnviarMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpEnviarMensagensLayout.setVerticalGroup(
            JpEnviarMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        JpConversa.add(JpEnviarMensagens);

        getContentPane().add(JpConversa);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JpTelaMensagens().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPainelContatos;
    private javax.swing.JPanel JpBuscarContatos;
    private javax.swing.JPanel JpContatosFrequentes;
    private javax.swing.JPanel JpConversa;
    private javax.swing.JPanel JpConversaAtual;
    private javax.swing.JPanel JpEnviarMensagens;
    private javax.swing.JPanel JpLogoProjeto;
    private javax.swing.JPanel JpPerfilContato;
    private javax.swing.JLabel jlConectaUFMS;
    private visao.TelaMensagens.JpMenuLateralEsquerdo jpMenuLateralEsquerdo1;
    // End of variables declaration//GEN-END:variables
}
