/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.TelaMensagens;

import Vo.VoContatos;
import Vo.VoLoginAluno;
import Vo.VoMensagem;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.border.EmptyBorder;
import regrasDeNegocio.ListaContatosRN;
import regrasDeNegocio.MensagemRN;
import visao.Componentes.MyButton;
import visao.Componentes.MyTextField;
import visao.TelaCadastroLogin.JpLogin;
import visao.TelaCadastroLogin.JpTelaLoginRegistro;
import java.awt.Toolkit;
/**
 *
 * @author Usuario
 */
public class JpTelaMensagens extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JpTelaMensagens.class.getName());

    private JPanel espacador;
    private JpTelaLoginRegistro telaprincipal;
    private String emailDestinatarioAtual;
    private SwingWorker<Void, Object[]> monitoramento;
    private JPainelAzul jpPainelAzul = new JPainelAzul();

    public JpTelaMensagens() {
        initComponents();
        iniciandoContatos();
        iniciandoTelaBemVindo();
        iniciandoComponentesMenuLateral();
        setLocationRelativeTo(null);
        setTitle("TelaConversa");

        JpPerfilContato.setVisible(false);
        JScrollMensagens.setVisible(false);
        JpEnviarMensagens.setVisible(false);

        VoLoginAluno loginAluno = new VoLoginAluno();
        jlNomeDoUsuario.setText(loginAluno.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenuLateralEsquerdo = new visao.TelaMensagens.JpMenuLateralEsquerdo();
        JPainelContatos = new javax.swing.JPanel();
        JpLogoProjeto = new javax.swing.JPanel();
        jlConectaUFMS = new javax.swing.JLabel();
        jlNomeDoUsuario = new javax.swing.JLabel();
        JpBuscarContatos = new javax.swing.JPanel();
        myTextField1 = new visao.Componentes.MyTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JpContatosFrequentes = new javax.swing.JPanel();
        JpConversa = new javax.swing.JPanel();
        JpPerfilContato = new javax.swing.JPanel();
        JScrollMensagens = new javax.swing.JScrollPane();
        JpConversaAtual = new javax.swing.JPanel();
        JpEnviarMensagens = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpMenuLateralEsquerdo.setMaximumSize(new java.awt.Dimension(60, 32767));
        jpMenuLateralEsquerdo.setMinimumSize(new java.awt.Dimension(60, 600));

        javax.swing.GroupLayout jpMenuLateralEsquerdoLayout = new javax.swing.GroupLayout(jpMenuLateralEsquerdo);
        jpMenuLateralEsquerdo.setLayout(jpMenuLateralEsquerdoLayout);
        jpMenuLateralEsquerdoLayout.setHorizontalGroup(
            jpMenuLateralEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jpMenuLateralEsquerdoLayout.setVerticalGroup(
            jpMenuLateralEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jpMenuLateralEsquerdo);

        JPainelContatos.setMaximumSize(new java.awt.Dimension(260, 50000));
        JPainelContatos.setMinimumSize(new java.awt.Dimension(260, 600));
        JPainelContatos.setLayout(new javax.swing.BoxLayout(JPainelContatos, javax.swing.BoxLayout.Y_AXIS));

        JpLogoProjeto.setBackground(new java.awt.Color(0, 82, 122));
        JpLogoProjeto.setMaximumSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setMinimumSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setPreferredSize(new java.awt.Dimension(260, 60));
        JpLogoProjeto.setRequestFocusEnabled(false);

        jlConectaUFMS.setBackground(new java.awt.Color(255, 255, 255));
        jlConectaUFMS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlConectaUFMS.setForeground(new java.awt.Color(255, 255, 255));
        jlConectaUFMS.setText("ConectaUFMS");
        jlConectaUFMS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlConectaUFMS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlConectaUFMSMouseClicked(evt);
            }
        });

        jlNomeDoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNomeDoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNomeDoUsuario.setText("nome");
        jlNomeDoUsuario.setName(""); // NOI18N

        javax.swing.GroupLayout JpLogoProjetoLayout = new javax.swing.GroupLayout(JpLogoProjeto);
        JpLogoProjeto.setLayout(JpLogoProjetoLayout);
        JpLogoProjetoLayout.setHorizontalGroup(
            JpLogoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLogoProjetoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(JpLogoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpLogoProjetoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlNomeDoUsuario))
                    .addComponent(jlConectaUFMS))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        JpLogoProjetoLayout.setVerticalGroup(
            JpLogoProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpLogoProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlConectaUFMS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jlNomeDoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPainelContatos.add(JpLogoProjeto);

        JpBuscarContatos.setBackground(new java.awt.Color(255, 255, 255));
        JpBuscarContatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        JpBuscarContatos.setMaximumSize(new java.awt.Dimension(260, 50));
        JpBuscarContatos.setMinimumSize(new java.awt.Dimension(260, 50));
        JpBuscarContatos.setPreferredSize(new java.awt.Dimension(260, 50));

        myTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpBuscarContatosLayout = new javax.swing.GroupLayout(JpBuscarContatos);
        JpBuscarContatos.setLayout(JpBuscarContatosLayout);
        JpBuscarContatosLayout.setHorizontalGroup(
            JpBuscarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpBuscarContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpBuscarContatosLayout.setVerticalGroup(
            JpBuscarContatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpBuscarContatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPainelContatos.add(JpBuscarContatos);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(260, 490));

        JpContatosFrequentes.setLayout(new javax.swing.BoxLayout(JpContatosFrequentes, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(JpContatosFrequentes);

        JPainelContatos.add(jScrollPane1);

        getContentPane().add(JPainelContatos);

        JpConversa.setMaximumSize(new java.awt.Dimension(50000, 50000));
        JpConversa.setMinimumSize(new java.awt.Dimension(680, 600));
        JpConversa.setLayout(new javax.swing.BoxLayout(JpConversa, javax.swing.BoxLayout.Y_AXIS));

        JpPerfilContato.setBackground(new java.awt.Color(255, 255, 255));
        JpPerfilContato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        JpPerfilContato.setMaximumSize(new java.awt.Dimension(32767, 60));
        JpPerfilContato.setMinimumSize(new java.awt.Dimension(680, 60));
        JpPerfilContato.setPreferredSize(new java.awt.Dimension(680, 60));

        javax.swing.GroupLayout JpPerfilContatoLayout = new javax.swing.GroupLayout(JpPerfilContato);
        JpPerfilContato.setLayout(JpPerfilContatoLayout);
        JpPerfilContatoLayout.setHorizontalGroup(
            JpPerfilContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpPerfilContatoLayout.setVerticalGroup(
            JpPerfilContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        JpConversa.add(JpPerfilContato);

        javax.swing.GroupLayout JpConversaAtualLayout = new javax.swing.GroupLayout(JpConversaAtual);
        JpConversaAtual.setLayout(JpConversaAtualLayout);
        JpConversaAtualLayout.setHorizontalGroup(
            JpConversaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpConversaAtualLayout.setVerticalGroup(
            JpConversaAtualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        JScrollMensagens.setViewportView(JpConversaAtual);

        JpConversa.add(JScrollMensagens);

        JpEnviarMensagens.setBackground(new java.awt.Color(255, 255, 255));
        JpEnviarMensagens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));
        JpEnviarMensagens.setMaximumSize(new java.awt.Dimension(32767, 50));
        JpEnviarMensagens.setMinimumSize(new java.awt.Dimension(680, 50));
        JpEnviarMensagens.setPreferredSize(new java.awt.Dimension(680, 50));

        javax.swing.GroupLayout JpEnviarMensagensLayout = new javax.swing.GroupLayout(JpEnviarMensagens);
        JpEnviarMensagens.setLayout(JpEnviarMensagensLayout);
        JpEnviarMensagensLayout.setHorizontalGroup(
            JpEnviarMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        JpEnviarMensagensLayout.setVerticalGroup(
            JpEnviarMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        JpConversa.add(JpEnviarMensagens);

        getContentPane().add(JpConversa);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myTextField1ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        JpEnviarMensagens.repaint();
    }//GEN-LAST:event_formWindowStateChanged

    private void jlConectaUFMSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlConectaUFMSMouseClicked

    }//GEN-LAST:event_jlConectaUFMSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JpTelaMensagens().setVisible(true));
    }

    private void iniciandoComponentesMenuLateral() {
        jpMenuLateralEsquerdo.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();

        VoLoginAluno loginAluno = new VoLoginAluno();

        JPainelArredondado perfil = new JPainelArredondado();
        perfil.setPreferredSize(new Dimension(50, 50));
        perfil.setBackground(new Color(60, 200, 230));
        
        perfil.setArredondandoBordas(50);

        JLabel letra = new JLabel(String.valueOf(loginAluno.getNome().charAt(0)));
        letra.setForeground(Color.WHITE);
        letra.setFont(new Font("Arial", Font.BOLD, 20));
        perfil.add(letra);

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.insets = new Insets(8, 5, 1, 5);
        jpMenuLateralEsquerdo.add(perfil, gbc);

        MyButton botaoSair = new MyButton();
        botaoSair.setPreferredSize(new Dimension(50, 50));
        botaoSair.setText("");
        botaoSair.setRadius(50);
        ImageIcon imagemSair = new ImageIcon(getClass().getResource("/Imagens/sair25px.png"));
        botaoSair.setIcon((Icon)imagemSair);
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 0;
        gbc.insets = new Insets(1, 5, 10, 5);
        jpMenuLateralEsquerdo.add(botaoSair, gbc);
        
        botaoSair.addActionListener(e -> saindoDoLogin());

    }

    private void iniciandoContatos() {
        VoContatos contatosVo = new VoContatos();
        new ListaContatosRN();

        List<String[]> listaContatos = contatosVo.getListaDeContatos();

        for (int i = 0; i < listaContatos.size(); i++) {
            String item[] = listaContatos.get(i);
            aparecendoContatos(item[1], item[0]);
        }
    }

    private void aparecendoContatos(String nome, String emailDestinatario) {

        JPanel painelContato = new JPanel();
        painelContato.setLayout(new GridBagLayout());
        painelContato.setBorder(BorderFactory.createLineBorder(Color.gray));

        painelContato.setPreferredSize(new Dimension(230, 80));
        painelContato.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));

        Random random = new Random();
        int r2 = random.nextInt(256); // 0-255
        int g2 = random.nextInt(256); // 0-255
        int b2 = random.nextInt(256); // 0-255

        //Configurando o começo do GridBagConstraints
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 10);
        gbc.anchor = GridBagConstraints.WEST;

        //Foto       
        int tamanhoDaFoto = 50;
        JPainelArredondado foto = new JPainelArredondado();
        foto.setPreferredSize(new Dimension(tamanhoDaFoto, tamanhoDaFoto));
        foto.setBackground(new Color(r2, g2, b2));
        foto.setLayout(new BorderLayout());
        foto.setArredondandoBordaBaixoDireta(tamanhoDaFoto);
        foto.setArredondandoBordaBaixoEsquerda(tamanhoDaFoto);
        foto.setArredondandoBordaCimaDireta(tamanhoDaFoto);
        foto.setArredondandoBordaCimaEsquerda(tamanhoDaFoto);

        JLabel letraFotoPerfil = new JLabel(String.valueOf(nome.charAt(0))); //Pegando primeira do nome e transformando para string
        letraFotoPerfil.setFont(new Font("Arial", Font.BOLD, 14));
        letraFotoPerfil.setForeground(Color.white);
        letraFotoPerfil.setHorizontalAlignment(SwingConstants.CENTER);
        letraFotoPerfil.setVerticalAlignment(SwingConstants.CENTER);
        foto.add(letraFotoPerfil);

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 1;
        painelContato.add(foto, gbc);

        gbc.gridheight = 1;

        //Nome da Pessoa
        JLabel jlNome = new JLabel(nome);
        jlNome.setFont(new Font("Arial", Font.BOLD, 12));
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1; // aqui que controla a parte da distancia
        gbc.anchor = GridBagConstraints.WEST;

        painelContato.add(jlNome, gbc);

        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        painelContato.setCursor(new Cursor(Cursor.HAND_CURSOR));
        painelContato.setBackground(Color.WHITE);
        painelContato.setVisible(true);

        //mudando de cor o painel quando passa a mão por cima
        painelContato.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                painelContato.setBackground(new Color(245, 245, 245));
                super.mouseEntered(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }

            @Override
            public void mouseExited(MouseEvent e) {
                painelContato.setBackground(Color.WHITE);
                super.mouseExited(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }

            VoLoginAluno loginUsuario = new VoLoginAluno();

            @Override
            public void mouseClicked(MouseEvent e) {
                if (JpPerfilContato.getComponentCount() > 0) {

                    JpPerfilContato.removeAll(); // Limpa todos os componentes do painel
                    JpPerfilContato.repaint(); //Redesenha o painel
                    chamandoPerfilContato(nome, r2, g2, b2);

                    JpConversaAtual.removeAll();
                    JpConversaAtual.repaint();
                    JpEnviarMensagens.removeAll();
                    JpEnviarMensagens.repaint();

                    chamandoTelaDeMensagens(emailDestinatario);

                } else {
                    jpPainelAzul.setVisible(false);
                    JpPerfilContato.setVisible(true);
                    JScrollMensagens.setVisible(true);
                    JpEnviarMensagens.setVisible(true);
                    chamandoPerfilContato(nome, r2, g2, b2);
                    chamandoTelaDeMensagens(emailDestinatario);
                }

                //Verificando se o monitoramento existe, se existir cancela ele
                if (monitoramento != null && !monitoramento.isCancelled()) {
                    monitoramento.cancel(true);
                }
                // Iniciando o SwingWorker para monitorar mensagens novas
                monitoramento = iniciarMonitoramentoDeMensagem(
                        loginUsuario.getEmail(),
                        emailDestinatario
                );

                super.mouseClicked(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }

        });

        //O jpContatosMensagem é o painel que vai ficar os contatos 
        JpContatosFrequentes.add(painelContato);
        JpContatosFrequentes.revalidate();
        JpContatosFrequentes.repaint();

    }

    private void chamandoPerfilContato(String nome, int r, int g, int b) {

        JpPerfilContato.setLayout(new GridBagLayout());
        JpPerfilContato.setBackground(Color.WHITE);
        JpPerfilContato.setBorder(BorderFactory.createLineBorder(Color.gray, 1));

        GridBagConstraints gbc = new GridBagConstraints();

        gbc.insets = new Insets(5, 10, 5, 1);
        gbc.anchor = GridBagConstraints.WEST;
        Font fonte = new Font("Arial", Font.BOLD, 14);

        JPainelArredondado foto = new JPainelArredondado();
        foto.setBackground(new Color(r, g, b));
        foto.setPreferredSize(new Dimension(45, 45));
        foto.setArredondandoBordaBaixoDireta(45);
        foto.setArredondandoBordaBaixoEsquerda(45);
        foto.setArredondandoBordaCimaDireta(45);
        foto.setArredondandoBordaCimaEsquerda(45);

        JLabel letraNome = new JLabel(String.valueOf(nome.charAt(0)));
        letraNome.setForeground(Color.WHITE);
        letraNome.setFont(new Font("Arial", Font.BOLD, 20));
        foto.setLayout(new GridBagLayout());
        foto.add(letraNome);

        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 2;

        JpPerfilContato.add(foto, gbc);

        gbc.gridheight = 1;
        gbc.insets = new Insets(8, 5, 5, 1);
        gbc.weightx = 1;

        JLabel jlNome = new JLabel(nome);
        jlNome.setFont(fonte);
        gbc.gridx = 1;
        gbc.gridy = 0;
        JpPerfilContato.add(jlNome, gbc);

        JLabel jlStatus = new JLabel("Offline");
        gbc.insets = new Insets(1, 5, 5, 1);
        jlStatus.setFont(fonte);
        gbc.gridx = 1;
        gbc.gridy = 1;
        JpPerfilContato.add(jlStatus, gbc);

        MyButton jbBaixarHistorico = new MyButton();
        jbBaixarHistorico.setPreferredSize(new Dimension(40, 40));
        jbBaixarHistorico.setRadius(40);
        gbc.insets = new Insets(5, 1, 5, 10);
        jbBaixarHistorico.setText("");
        ImageIcon imagemBaixar = new ImageIcon(getClass().getResource("/Imagens/baixarHistorico40px.png"));
        jbBaixarHistorico.setIcon((Icon)imagemBaixar);
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 0;

        JpPerfilContato.add(jbBaixarHistorico, gbc);
        
        jbBaixarHistorico.addActionListener(e -> baixarHistoricoMensagens());
        
        JpPerfilContato.revalidate();
        JpPerfilContato.repaint();
    }

    private void chamandoTelaDeMensagens(String emailDestinatario) {

        //Parte das Mensagens
        JpConversaAtual.setLayout(new GridBagLayout());
        JpConversaAtual.setBackground(new Color(230, 230, 230));

        // Criando um espaçador para enpurrar as mensagens para cima
        espacador = new JPanel();
        espacador.setOpaque(false);
        GridBagConstraints gbcEspacador = new GridBagConstraints();
        gbcEspacador.gridwidth = GridBagConstraints.REMAINDER;
        gbcEspacador.weighty = 1.0;
        gbcEspacador.fill = GridBagConstraints.VERTICAL;
        JpConversaAtual.add(espacador, gbcEspacador);

        //Criando botões para escrever a mensagem e enviar a mensagem
        // Painel
        JpEnviarMensagens.setLayout(new BorderLayout());
        JpEnviarMensagens.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Campo
        MyTextField mtfdCampoEscreverMensagens = new MyTextField();
        mtfdCampoEscreverMensagens.setText("");
        JpEnviarMensagens.add(mtfdCampoEscreverMensagens, BorderLayout.CENTER);

        //Botão
        MyButton mbEnviar = new MyButton();
        mbEnviar.setText("Enviar");

        this.emailDestinatarioAtual = emailDestinatario;
        mbEnviar.addActionListener(e -> {
            String texto = mtfdCampoEscreverMensagens.getText();

            if (!texto.isEmpty()) {

                mtfdCampoEscreverMensagens.setText("");
                VoLoginAluno loginAluno = new VoLoginAluno();

                //salvando no banco a mensagem
                salvandoMensagens(this.emailDestinatarioAtual, loginAluno.getEmail(), texto);

            }

        });
        JpEnviarMensagens.add(mbEnviar, BorderLayout.EAST);

    }

    private void adicionarMensagem(String texto, boolean usuario) {

        // Remover o espacador temporariamente
        JpConversaAtual.remove(espacador);

        JPainelArredondado bolhaMensagem = new JPainelArredondado();
        bolhaMensagem.setLayout(new BorderLayout());
        bolhaMensagem.setBorder(new EmptyBorder(5, 10, 5, 10));

        JLabel lbl = new JLabel("<html><p style='width:200px'>" + texto + "</p></html>");
        lbl.setOpaque(false);
        lbl.setBorder(new EmptyBorder(10, 10, 10, 10));

        int tamanhoBordaMensagem = 20;
        if (usuario) {
            // Mensagem do usuário - direita (cor verde)
            lbl.setForeground(Color.WHITE);
            bolhaMensagem.setBackground(new Color(8, 136, 183));
            bolhaMensagem.setArredondandoBordaBaixoDireta(tamanhoBordaMensagem);
            bolhaMensagem.setArredondandoBordaBaixoEsquerda(tamanhoBordaMensagem);
            bolhaMensagem.setArredondandoBordaCimaEsquerda(tamanhoBordaMensagem);
            bolhaMensagem.add(lbl, BorderLayout.EAST);
        } else {
            // Mensagem recebida - esquerda (cor branca)
            lbl.setForeground(Color.BLACK);
            bolhaMensagem.setBackground(Color.WHITE);
            bolhaMensagem.setArredondandoBordaBaixoDireta(tamanhoBordaMensagem);
            bolhaMensagem.setArredondandoBordaBaixoEsquerda(tamanhoBordaMensagem);
            bolhaMensagem.setArredondandoBordaCimaDireta(tamanhoBordaMensagem);
            bolhaMensagem.add(lbl, BorderLayout.WEST);
        }

        // Configurar GridBagConstraints para controlar o posicionamento
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER; // Ocupa a linha inteira
        gbc.fill = GridBagConstraints.NONE; // NÃO estica os componentes
        gbc.anchor = usuario ? GridBagConstraints.EAST : GridBagConstraints.WEST; // Alinha direita/esquerda
        gbc.insets = new Insets(2, 10, 2, 10); // Espaçamento entre mensagens
        gbc.weightx = 1.0; // Ocupa toda a largura disponível horizontalmente
        gbc.weighty = 0.0; // Não expande verticalmente

        JpConversaAtual.add(bolhaMensagem, gbc);

        // Re-adicionar o espacador no final (isso empurra tudo para cima)
        GridBagConstraints gbcEspacador = new GridBagConstraints();
        gbcEspacador.gridwidth = GridBagConstraints.REMAINDER;
        gbcEspacador.weighty = 1.0; // Isso é o segredo - empurra as mensagens para cima
        gbcEspacador.fill = GridBagConstraints.VERTICAL;
        JpConversaAtual.add(espacador, gbcEspacador);

        JpConversaAtual.revalidate();
        JpConversaAtual.repaint();

        // Scroll desce automaticamente
        SwingUtilities.invokeLater(() -> {
            JScrollBar barra = JScrollMensagens.getVerticalScrollBar();
            barra.setValue(barra.getMaximum());
        });

    }

    private void salvandoMensagens(String emailDestinatario, String emailDono, String mensagemCampo) {
        VoMensagem mensagem = new VoMensagem();
        mensagem.setEmailDono(emailDono);
        mensagem.setEmailDestinatario(emailDestinatario);
        mensagem.setMensagem(mensagemCampo);

        MensagemRN mensagemRN = new MensagemRN();
        mensagemRN.salvandoMensagemRN(mensagem);

    }



    private SwingWorker iniciarMonitoramentoDeMensagem(
            String emailDono,
            String emailDestinatario
    ) {
        SwingWorker<Void, Object[]> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                MensagemRN mensagens = new MensagemRN();

                long ultimasQuantidade = 0;

                while (!isCancelled()) {
                    Object[][] mensagensConversa = mensagens.buscandoMensagens(emailDono, emailDestinatario);
                    long quantidadeAtual = mensagensConversa.length;

                    if (quantidadeAtual > ultimasQuantidade) {
                        for (int i = (int) ultimasQuantidade; i < quantidadeAtual; i++) {

                            publish(mensagensConversa[i]);
                        }
                        ultimasQuantidade = quantidadeAtual;
                        SwingUtilities.invokeLater(() -> {
                            Toolkit.getDefaultToolkit().beep();
                        });
                    }

                    Thread.sleep(5000);
                }
                return null;
            }

            @Override
            protected void process(List<Object[]> chunks) {

                for (int i = 0; i < chunks.size(); i++) {
                    String texto = String.valueOf(chunks.get(i)[0]);
                    boolean usuario = Boolean.TRUE.equals(chunks.get(i)[1]);
                    adicionarMensagem(texto, usuario);
;
                }

                super.process(chunks);
            }

        };

        worker.execute();
        return worker;

    }

    private void iniciandoTelaBemVindo() {
        JpPerfilContato.setVisible(false);
        JScrollMensagens.setVisible(false);
        JpEnviarMensagens.setVisible(false);

        jpPainelAzul.setMaximumSize(new Dimension(50000, 50000));
        jpPainelAzul.setMinimumSize(new Dimension(680, 600));
        jpPainelAzul.setPreferredSize(new Dimension(680, 600));
        JpConversa.add(jpPainelAzul);

    }
    
    private void saindoDoLogin() {
        VoLoginAluno loginAluno = new VoLoginAluno();
        loginAluno.setEmail("");
        loginAluno.setNome("");
        dispose();
        JpLogin telaLogin = new JpLogin();
        telaLogin.getTelaPrincipal().setVisible(true);
    }
    
    private void baixarHistoricoMensagens() {
        System.out.println("Baixando Historico.....");
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPainelContatos;
    private javax.swing.JScrollPane JScrollMensagens;
    private javax.swing.JPanel JpBuscarContatos;
    private javax.swing.JPanel JpContatosFrequentes;
    private javax.swing.JPanel JpConversa;
    private javax.swing.JPanel JpConversaAtual;
    private javax.swing.JPanel JpEnviarMensagens;
    private javax.swing.JPanel JpLogoProjeto;
    private javax.swing.JPanel JpPerfilContato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlConectaUFMS;
    private javax.swing.JLabel jlNomeDoUsuario;
    private visao.TelaMensagens.JpMenuLateralEsquerdo jpMenuLateralEsquerdo;
    private visao.Componentes.MyTextField myTextField1;
    // End of variables declaration//GEN-END:variables




}
